### ISSUE TITLE
Underscores for emphasis not always rendering

### ISSUE THREAD

**Issue by logista** [leipert/language-pfm#11]
I use `underscore` to denote titles and foreign words, and `asterisk` to denote emphasis. _The asterisk_ works in all occasions. The _underscore_ does not, unless the underscored item is after punctuation.

language-pfm rendering:
![screen shot 2015-09-09 at 11 35 04](https://cloud.githubusercontent.com/assets/4933215/9766533/6eaa9982-56e7-11e5-895c-8120d139d783.png)

language-gfm rendering:
![screen shot 2015-09-09 at 11 36 10](https://cloud.githubusercontent.com/assets/4933215/9766538/7a3c7946-56e7-11e5-8f4b-cd9713bc6272.png)

**Comment by ZelphirKaltstahl** [comment]
I can confirm this. For me the issue looks a bit different in result though. Here is a screenshot:

![atom4](https://cloud.githubusercontent.com/assets/11130348/15126175/114fe166-1631-11e6-8d1c-c73514943fb9.png)

So it seems it doesn't highlight emphasis, if the next thing to the underscores is an alphanumeric character. When I replace the underscores with asterisks, there is no such issue. I also prefer underscores over asterisks btw.

**Comment by ZelphirKaltstahl** [comment]
I fixed this on my fork. I only needed to remove part of the regular expression responsible for marking up the underscore emphasis region. Made a pull request, but you should be able to use my fork, if it doesn't get pulled.

**Comment by logista** [comment]
@ZelphirKaltstahl That worked! Thank you.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
