### ISSUE TITLE
Adding additional languages to fenced code blocks

### ISSUE THREAD

**Issue by tshort** [leipert/language-pfm#12]
This is more of an inquiry. Is it possible to customize language-gfm locally to add languages used with fenced code blocks? 

I see the code here:

https://github.com/leipert/language-pfm/blob/dist/grammars/pfm.cson#L1444

I'd like to add support for [langulage-slim](https://github.com/slim-template/language-slim).

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
