### ISSUE TITLE
Asterisks not highlighted immediately after list asterisk

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [leipert/language-pfm#13]
I'd like to add a screenshot, however, I could find no such option in this editor, so I'll describe the issue only using words.

When you start an unordered list using the asterisk character and then start italic text immediately after inserting exactly one space, the asterisks of the italic text and the italic text are not highlighted as italic text, they do not get colored purple like they usually do. However, if you enter two spaces after the asterisk of the list instead, it works as expected. When I compile the list with exactly one space to a PDF (using pandoc) the PDF has correct rendering.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
