### ISSUE TITLE
Disabling language-gfm

### ISSUE THREAD

**Issue by 7Moses** [leipert/language-pfm#14]
Hello, I have language-pfm installed; I have been trying to disable language-gfm. In language syntax (ctrl-shift-l) I see two items for GitHub Markdown, disabling language-gfm removes only one of those items. My default remains GitHub Flavored Markdown. 

{I am wondering if I have a second copy of the package, l -gfm,, but currently cannot locate it,}

I have tried tweaking config.cson

Thanks for any guidance,

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
