### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [leipert/language-pfm#16]
<s>Where is the promised Math support?</s>

<s>Display style math blocks using `$$` and `$$` don't get highlighted at all ... check this screenshot:</s>

![atom6](https://cloud.githubusercontent.com/assets/11130348/15126286/98ac908c-1631-11e6-88b5-990fa53639b3.png)

<s>_Note_: The white color and dotted border are from my user stylesheet. Otherwise there would be NO highlighting at all.</s>

<s>**EDIT**: This is an issue with the selected _Theme_, not with this package! You need to select a theme, which distinguishes math from regular text. This issue may be closed.</s>

It seems the `language-pfm` package only distinguishes two elements of the math blocks. Those two are: `punctuation definition constant math tex` and `constant character math tex`.

I think it would be desirable to extend the packages support for math and distinguish operators like `+`, `-`, `*`, `/`, `^` and `_`. Variables should also be marked up.

**Comment by mangecoeur** [comment]
I helped add Latex support to language-rst, it's possible to simply include the pre-installed LaTex grammer into the math scope (language-pfm currently defines it's own maths). I think using the installed latex grammer is a better solution https://github.com/Lukasa/language-restructuredtext/issues/44

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
