### ISSUE TITLE
knitr / r syntax support

### ISSUE THREAD

**Issue by maxheld83** [leipert/language-pfm#2]
It would be great if this package would support code highlighting for inline and fenced R via knitr – that would effectively make this into an [Rmarkdown](http://rmarkdown.rstudio.com) highlighter, which is otherwise just Pandoc Markdown.

**Comment by maxheld83** [comment]
actually same as https://github.com/christophergandrud/language-knitr/issues/1

**Comment by leipert** [comment]
@maxheld83 I stole the math highlighting from the latex package. Does a R/knitr highlighting package already exist?

**Comment by maxheld83** [comment]
yes @leipert – https://github.com/christophergandrud/language-knitr does knitr highlighting and R is in https://github.com/lee-dohm/language-r

**Comment by leipert** [comment]
Hey there, I tried to implemented it. Unfortunately I am not familiar with R and Knitr.
Does this look good to you?

<img width="702" alt="screen shot 2015-07-05 at 11 38 43" src="https://cloud.githubusercontent.com/assets/2906107/8511143/8f0447ca-230a-11e5-961b-5626a68fbd5f.png">

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
