### ISSUE TITLE
Support for line_block extension

### ISSUE THREAD

**Issue by siovan** [leipert/language-pfm#20]
Pandoc allows for a special kind of block quote marked with a | in which:
   
> The division into lines will be preserved in the output, as will any leading spaces; otherwise, the lines will be formatted as Markdown. This is useful for verse and addresses.

[From pandoc](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#line_blocks)

I use this environment all the time since I'm a scholar who writes about poetry. I have only the most basic programming skills and can't figure out where to start, but I'm happy to give it a go myself if someone would be willing to point me in the right direction.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
