### ISSUE TITLE
support (or even just ignore) raw LaTeX 

### ISSUE THREAD

**Issue by crmackay** [leipert/language-pfm#22]
So when using raw LaTeX, it seems like the syntax highlighter is tripping up on backticks. 

See here:
![image](https://cloud.githubusercontent.com/assets/3801862/22523467/8e4dff7a-e88d-11e6-8559-4ef485f5dbc0.png)

Seems like its trying to parse the two backticks as an inline verbatim element. 

I think, if possible, it might be preferable to just ignore text in between a `\begin{environment}...\end{environment}`. Pandoc understands these to be a raw block of latex, so even if they are just set aside and treated as *not* markdown, that would be fine with me.

the code for replication is here:

```latex
\begin{equation}
\begin{array}{ll}
M(q_k, s_k) = & \left \{
	\begin{array}{ll}
		m & if (q_k = s_k) \\
		x & if (q_k \neq s_k) \\
		n & if (q_k = ``N") \\
	\end{array}
	\right .
\end{array}
\end{equation}

$P(S|L,m)_k$ is a function of ...
```

Thanks for the great package, and let me know if you need anything else.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
