### ISSUE TITLE
fenced code block syntax: yaml syntax detection skips past closing fence

### ISSUE THREAD

**Issue by crmackay** [leipert/language-pfm#23]
When including a block of `yaml` text in a fenced codeblock, the syntax detection for yaml kicks in, however it seems to blow right past the closing fence (the closing triple backticks). It seems to be looking for a yaml metadata block closing sequence (`---`). When I include a triple hyphen, the yaml syntax stops and the document continues normally.
 
![image](https://cloud.githubusercontent.com/assets/3801862/22846220/7b156212-efb4-11e6-9819-66fabee0847f.png)

![image](https://cloud.githubusercontent.com/assets/3801862/22846185/4a6fe1fa-efb4-11e6-839e-f85a6831fc98.png)

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
