### ISSUE TITLE
YAML headers closed with "..." do not end YAML highlighting

### ISSUE THREAD

**Issue by jpeacock29** [leipert/language-pfm#24]
Pandoc markdown allows YAML headers to end with either "---" or "...", on a separate line. YAML headers ending with "---" behaive correctly, while those ending in "..." do not end the YAML syntax highlighting and the rest of the document is treated as YAML.

For example,
```
---
key: value
keys: [values, values]
...
```
would cause the rest of the document to have YAML syntax highlighting, not just the YAML header. As a work around, one could equivalently use,
```
---
key: value
keys: [values, values]
---
```

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)

**Comment by jpeacock29** [comment]
No worries, thanks for your eventual response! For others who might find this page, the [language-markdown](https://atom.io/packages/language-markdown) package now offers full support here.
