### ISSUE TITLE
Fenced code attributes break syntax highlighting

### ISSUE THREAD

**Issue by LenGrispani** [leipert/language-pfm#26]
Syntax highlighting is not applied to any text following a region of code defined using fenced code attributes.

```
# This Heading is Highlighted

~~~ {#lst:SC caption="Some Code" .cs}
  Code Here
~~~

# This Heading is NOT Highlighted
```
I love `language-pfm` but need to use those fenced code attributes. 

Thanks!

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
