### ISSUE TITLE
Long lines break syntax highlighting

### ISSUE THREAD

**Issue by kredati** [leipert/language-pfm#27]
As noted at the end of https://github.com/atom/atom/issues/1667, text at the end of long lines doesn't get syntax highlighting; the max line length for syntax highlighting Atom-wide is 1000 chars. Those of us writing prose often get longer than 1000 chars in a paragraph.

This can be fixed easily: add `limitLineLength: no` to the grammar file.

Happy to submit at PR to fix, but wanted to file an issue first to make sure there aren't issues I'm not aware of.

**Comment by vitopepito** [comment]
I enjoy the added highlights for pandoc, but this annoys me as well!

**Comment by thokaro** [comment]
Where can i find the grammar files?

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
