### ISSUE TITLE
markup.footnote.inline.pfm matching pattern doesn't end propperly

### ISSUE THREAD

**Issue by olafklingt** [leipert/language-pfm#28]
when i use inline footnotes like the following ^[this is the content of the footnote] than the following text is highlighted as footnote until the next footnote ^[which is here] ...

I changed the matching pattern in the grammar file but i am not sure if it is valid for all cases as it is much simpler than the original one:

name: 'markup.footnote.inline.pfm'
match: '(\\^\\[)([^\\^]*?)(\\])'

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
