### ISSUE TITLE
Syntax for automatic links is not correct

### ISSUE THREAD

**Issue by robinrosenstock** [leipert/language-pfm#29]
when syntax highlighting the following text with language-pfm:

~~~markdown
this is correct: https://test.com
as can be seen in this line
as can be seen in this line
as can be seen in this line
this is false: <https://test.com>
as can be seen in this line
as can be seen in this line
as can be seen in this line
~~~

it looks like this with the [seti syntax theme](https://atom.io/themes/seti-syntax):

![screenshot_20180225_152007](https://user-images.githubusercontent.com/6190906/36642412-5f92f5d4-1a3f-11e8-869c-d2d11e6e9df8.png)

The first link will have the correct scope: `markup.underline.link.https.hyperlink`. But the second will be interpreted as an html tag and all (normal) text after the '>' sign will be of scope `source.html.basic`, which is obviously false.
Apparently it does not recognize the [automatic links from pandoc](http://pandoc.org/MANUAL.html#automatic-links).

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
