### ISSUE TITLE
stop styling of blockquote at beginning of citation marker

### ISSUE THREAD

**Issue by nylki** [leipert/language-pfm#3]
the following two examples are all scoped as `comment.quote` including the citation markers `[S.175]` and `^[S.175]`:

normal citation:
`> "This is a quote is a quote is a quote, saying very useful things in relation to the rest of the text."[@author]`

footnote:
`> "This is a quote is a quote is a quote, saying very useful things in relation to the rest of the text."^[compare to @author]`

Better would be to have that scope until (excluding) the `[` or the `^` which indicates a citation for pandoc, so that the citation markers would regain their own styling, even when directly after a blockquote.

**Comment by leipert** [comment]
Is it good like this?

<img width="892" alt="screen shot 2015-07-05 at 17 33 49" src="https://cloud.githubusercontent.com/assets/2906107/8512271/0ef4aade-233c-11e5-8073-559bf95d96a2.png">

**Comment by nylki** [comment]
~~Yes. As long as the prefix (in your example `compare to`) can be styled independently, which it seemingly is in the second example (bold type).~~

edit: I just checked out your latest push. Let me see what you exactly did and then I'll give new feedback. :)
edit2: It's good this way now!

Btw. I like your use of superscript. Not sure if it makes sense for longer footnotes though. Will experiment with it.

**Comment by nylki** [comment]
I found a bug:
when a quote has brackets inside, there seems to be a conflict with citation brackets as soon as there is a citekey.

how it should be styled. without brackets in quote.
![bildschirmfoto von 2015-07-06 15-45-48](https://cloud.githubusercontent.com/assets/1710598/8523523/2da85380-23f6-11e5-8e70-08a22b1cb210.png)

mention of author, and brackts in quote. This show the undesired behaviour.
![bildschirmfoto von 2015-07-06 15-45-33](https://cloud.githubusercontent.com/assets/1710598/8523524/2daa383a-23f6-11e5-8c00-6568d235a071.png)

interestingly, the problem arises only if the citekey is more than one character.
![bildschirmfoto von 2015-07-06 15-45-13](https://cloud.githubusercontent.com/assets/1710598/8523522/2da77988-23f6-11e5-8bdc-1de9ebc75dfa.png)

**Comment by leipert** [comment]
Ha, funny. Will have a look :dancer: 

Yes, it may be hacky within css, but I see no other way to do this.

**Comment by nylki** [comment]
I found another curious thing
![bildschirmfoto von 2015-07-06 15-57-54](https://cloud.githubusercontent.com/assets/1710598/8523830/de852c9a-23f7-11e5-8824-e21b2354c949.png)

I suppose it does that, because in the footnote sample the block begins at `p.1` whereas in the first on it begin with `[` which is standard text.

It would be cool though to mark the `[` and `]` as `.support`. And the text inside as a separate class. So you could style a list like normal text, as it might not be a good idea to style page abbreviations (p., S.) as list. Does this look like a good idea to you?

**Comment by nylki** [comment]
Hey there @leipert! :)
Just wanted to ask, wether you found a solution yet, not urgent though.

**Comment by nylki** [comment]
Btw. somebody found another unwanted behaviour when having a footnote with a standard citation in one line, thought I'd link it here, in case you want to investigate.
![](https://cloud.githubusercontent.com/assets/8274140/10236378/0b1d895e-68a5-11e5-9ba9-b7e2bc981054.png)
https://github.com/nylki/pen-paper-coffee-syntax/issues/20#issuecomment-144845830

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
