### ISSUE TITLE
Footnote highlighting support

### ISSUE THREAD

**Issue by tomak-git** [leipert/language-pfm#4]
First of all, thanks for creating the package!

Just a note to make it better -- it looks like footnotes are not treated properly. The footnote signs within a paragraph (aka `[^1]`) are not highlighted at all and the footnotes themselves (aka `[^1]: footnote contents` are highlighted incorrectly as if they are links, i.e. it highlights the contents of the brackets and the first word of the footnote contents (which is how normal gfm-language treats pandoc markdown footnotes).

Here is a sample text that should indicate what I'm talking about:

<code>
This is a testing document for testing purposes only. This is a
testing document for `testing` purposes only.[^1] This is a testing
document for testing purposes only. This is a testing document for
testing purposes only.

[^1]: This is a footnote.
</code>

**Comment by leipert** [comment]
Fixed: 
<img width="830" alt="screen shot 2015-07-05 at 17 33 57" src="https://cloud.githubusercontent.com/assets/2906107/8512273/217842d8-233c-11e5-8049-ccb005395b45.png">
