### ISSUE TITLE
Add scope for citation segments

### ISSUE THREAD

**Issue by mangecoeur** [leipert/language-pfm#6]
The name in pandoc-style @-citations like  `@Zucchini2000` gets the `string.username.gfm` scope while the `@` gets `variable.mention.gfm`

It would be nice if the whole  `@Zucchini2000` chunk also got something like a `markup.ref.pfm` scope to make it easier to do things with citations (e.g. to get the citekey under the cursor) - it's obviously possible using `username.gfm` but it would be cleaner with its own scope.

**Comment by stefanprobst** [comment]
I actually do get `markup.citation.pfm` when the citation is between brackets like [@author2016], but not without the brackets.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
