### ISSUE TITLE
snippets can be annoying

### ISSUE THREAD

**Issue by mangecoeur** [leipert/language-pfm#7]
I'm using pfm for long-form documents and I'm finding the snippets included can be annoying because they bring up the autocompletion menu as you are typing - since the snippets are keyed to common letters they are always popping up as you type which gets distracting. It would be nice to be able to disable them somehow (or maybe have them as a separate package?) at the moment I edit the package source.

For the bold/italic it might be nice to rather add keyboard shortcuts as in rich text editors (<kbd>CMD-b</kbd>, <kbd>CMD-i</kbd>)

**Comment by nylki** [comment]
In case you don't want any autocompletion at all in markdown/pfm (including other autocompletions for non-snippets) you can go to you `autocomplete-plus` -> _settings_, and add `.md` or the file blacklist or `.pfm` to the scope blacklist. As mentioned this would disable _all_ autocompletion for pfm files.

**Comment by mangecoeur** [comment]
the problem is I DO want autocomplete but just for specific things (e.g. my custom snippets and bibtex autocomplete). For Autocomplete plugins you can set the priority and tell them to silence lower priority completions, however it seems snippets completions always show.

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
