### ISSUE TITLE
Use different styling for blockquotes

### ISSUE THREAD

**Issue by adunning** [leipert/language-pfm#8]
If I am understanding the code correctly, the same styling is used for comments and block quotations, which makes them difficult to distinguish. The grey italics (as rendered in Atom, One, Solarized, etc.) are nice for comments, but are difficult to read at length, and make it easy to miss the use of actual italic markup within these. I would suggest following TextMate, which renders block quotations with a dark alternate colour.

(And thank you for this package; it makes using Atom and Pandoc far more enjoyable.)

**Comment by leipert** [comment]
Sorry for never responding. I am unable to maintain this project (see also #31)
